### ISSUE TITLE
error: use of undeclared identifier 'MSHookMemory'

### ISSUE THREAD

**Issue by Rednick16** [Cryptiiiic/fate#1]
![F544AB31-4049-45DF-8762-174E2E6B66A2](https://user-images.githubusercontent.com/71528727/93644609-fad08880-f9c7-11ea-9353-9c63dd5f6a53.png)

**Comment by Cryptiiiic** [comment]
You need latest theos... and updated submodules, this error is nothing to do with this project, closing.
